version: "3.9"

services:
  # PHP-FPM + Laravel
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    expose: 
      - 9000
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db
      - minio
    networks:
      - laravel

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
      # - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: application_letters
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sirapel
      MYSQL_PASSWORD: sirapel123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel

  # MinIO (object storage)
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: applicationletters
      MINIO_DEFAULT_REGION: us-east-1
      MINIO_USE_PATH_STYLE_ENDPOINT: true
    ports:
      - "9003:9000"
      - "9004:9001"
    volumes:
      - minio_data:/data
    networks:
      - laravel

  # OnlyOffice
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    environment:
      JWT_ENABLED: "false"
    restart: always
    ports:
      - "8010:80"
    networks:
      - laravel

volumes:
  db_data:
  minio_data:

networks:
  laravel:
    driver: bridge
